services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: terava_db
            MYSQL_USER: terava
            MYSQL_PASSWORD: terava
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: rootpassword
        ports:
            - "8080:80"
        depends_on:
            - mysql

volumes:
    mysql_data:


